const scienceFacts = [
    "The Sun is a big, hot ball of fire in the sky.",
    "Earth is our home planet, and it spins around like a top.",
    "The Moon is our neighbor in space, and it reflects light from the Sun at night.",
    "Stars are like faraway Suns that twinkle in the night sky.",
    "Mars is a red planet, and scientists send robots to explore it.",
    "Astronauts are people who travel to space and float in zero gravity.",
    "Saturn is a planet with beautiful rings made of ice and rocks.",
    "Gravity is what keeps us on the ground and makes things fall down.",
    "The International Space Station is like a floating home for astronauts in space.",
    "Telescopes help scientists see faraway planets and galaxies in space.",
    "Comets are icy snowballs that zoom around in space with long tails.",
    "Jupiter is the biggest planet in our solar system.",
    "A light year is a really, really big distance that light travels in one year.",
    "Black holes are mysterious places in space with super strong gravity.",
    "Our galaxy is called the Milky Way, and it's full of stars.",
    "NASA is a space agency that sends rockets and robots to explore space.",
    "Rovers are robots that drive around on other planets, like Mars.",
    "Astronomy is the study of stars, planets, and everything in space.",
    "Neil Armstrong was the first person to walk on the Moon in 1969.",
    "Space shuttles were like space cars that took astronauts to space.",
    "A light speed spaceship would take a really long time to reach other stars.",
    "Telescopes on Earth and in space help us learn about the universe.",
    "The Hubble Space Telescope takes amazing pictures of distant galaxies.",
    "Mercury is the closest planet to the Sun and gets really hot.",
    "A light minute is the distance light travels in one minute.",
    "A day on Jupiter is shorter than a day on Earth.",
    "Uranus is a sideways planet that rolls around the Sun.",
    "A space probe called Voyager 1 is traveling outside our solar system.",
    "A solar eclipse happens when the Moon covers the Sun for a little while.",
    "Astronomy is like a big puzzle, and scientists use telescopes to solve it.",
    "Scientists dream of finding planets in space where aliens might live."
];
const artFacts = [
    "Art is a way to express feelings and ideas using colors and shapes.",
    "Paintings are pictures that artists create with brushes and paint.",
    "Leonardo da Vinci was a famous artist who painted the Mona Lisa.",
    "Vincent van Gogh was an artist who painted Starry Night and cut off part of his own ear.",
    "Sculptures are 3D artworks made by carving or shaping materials like clay or stone.",
    "Pablo Picasso was an artist who painted faces in a funny way called Cubism.",
    "The color wheel helps artists choose and mix colors to create beautiful pictures.",
    "Claude Monet was an artist who liked to paint water lilies and gardens.",
    "Abstract art is when artists use shapes and colors to create something that doesn't look like real things.",
    "Georgia O'Keeffe painted big flowers and landscapes that look like they're up close.",
    "Michelangelo was a famous sculptor who carved a giant statue called David.",
    "Watercolors are a type of paint that artists use with water to create soft, flowing pictures.",
    "Frida Kahlo was a painter who liked to paint self-portraits and include symbols from her life.",
    "Andy Warhol made art with pictures of things like soup cans and Marilyn Monroe, called Pop Art.",
    "Ancient Egyptians used hieroglyphics, a kind of picture writing, to tell stories on walls.",
    "Renaissance means a time of great creativity and learning in art, science, and more.",
    "Jackson Pollock was an artist who dripped and splattered paint to make unique, abstract art.",
    "Collage is when artists glue together different materials to make a picture or design.",
    "Henri Matisse made colorful cut-out art by snipping shapes from colored paper.",
    "Cave paintings were some of the first artworks made by early humans on the walls of caves.",
    "Vincent van Gogh's paintings often have swirling, energetic brushstrokes.",
    "Mosaics are artworks made by arranging small colored pieces, like tiles, into a pattern or picture.",
    "Artists use shading to make things look 3D by adding darker areas to show shadows.",
    "Diego Rivera was a muralist who painted large artworks on walls to tell stories.",
    "Raphael was an artist during the Renaissance known for his beautiful paintings of angels and people.",
    "Printmaking is a technique where artists make copies of their artwork using stamps or plates.",
    "Salvador Dalí painted surreal, dreamlike pictures with melting clocks and strange shapes.",
    "Crayons, markers, and pencils are tools artists use to draw and color pictures.",
    "Pointillism is a style of art where tiny dots of color are used to create a larger image.",
    "Escher made art that played with optical illusions, making you see things in tricky ways.",
    "Piet Mondrian painted with rectangles and squares in primary colors, like red, blue, and yellow."
];
const historyFacts = [
    "Christopher Columbus sailed across the ocean in 1492 and discovered America.",
    "Abraham Lincoln was a president who helped end slavery in the United States.",
    "The Great Wall of China was built a long time ago to protect against invaders.",
    "Ancient Egyptians built pyramids as tombs for their pharaohs, filled with treasures.",
    "The Titanic was a big ship that sank in 1912, and it's a famous story.",
    "Joan of Arc was a brave girl who helped France in a war a long time ago.",
    "The Declaration of Independence was written in 1776, declaring freedom for the United States.",
    "The first airplane was flown by the Wright brothers, Orville and Wilbur, in 1903.",
    "The Vikings were explorers who sailed in longships a long time ago.",
    "George Washington was the first president of the United States.",
    "Ancient Greeks created the Olympics, where athletes from around the world compete.",
    "Martin Luther King Jr. had a dream of equality for all people, and he fought for it.",
    "The pyramids of Egypt were built as tombs for pharaohs, kings of ancient Egypt.",
    "Rosa Parks was a brave woman who helped start the Civil Rights Movement in the U.S.",
    "Marco Polo was an explorer who traveled the Silk Road and wrote about his adventures.",
    "The Industrial Revolution changed how things were made with machines and factories.",
    "Harriet Tubman was a courageous woman who helped slaves escape through the Underground Railroad.",
    "The Aztecs were a civilization in Mexico known for their pyramids and calendar.",
    "The Renaissance was a time of creativity and learning in Europe.",
    "Sacagawea was a Native American woman who helped Lewis and Clark explore the West.",
    "The Battle of Gettysburg was an important battle during the American Civil War.",
    "Ancient Romans built a great empire, and they had gladiator games in big arenas.",
    "The Mayflower was a ship that brought the Pilgrims to America in 1620.",
    "Neil Armstrong was the first person to walk on the Moon in 1969.",
    "Machu Picchu is an ancient city in the mountains of Peru built by the Inca civilization.",
    "The Cold War was a time of tension between the United States and the Soviet Union.",
    "Susan B. Anthony fought for women's right to vote in the United States.",
    "The Underground Railroad was a network of safe houses that helped slaves escape to freedom.",
    "The Boston Tea Party was a protest by American colonists against British taxes.",
    "Alexander the Great was a famous conqueror who built a huge empire in ancient times."
];

export { scienceFacts, artFacts, historyFacts }